# documentation: https://appsmith.com
# slogan: Appsmith is low-code application platform for building internal tools.
# tags: lowcode,nocode,no,low,platform
# logo: svgs/appsmith.svg

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:latest
    environment:
      - SERVICE_FQDN_APPSMITH
      - APPSMITH_MAIL_ENABLED=false
      - APPSMITH_DISABLE_TELEMETRY=true
      - APPSMITH_DISABLE_INTERCOM=true
      - APPSMITH_SENTRY_DSN=
      - APPSMITH_SMART_LOOK_ID=
    volumes:
      - stacks-data:/appsmith-stacks
    healthcheck:
      test: ["NONE"]
