# documentation: https://github.com/dani-garcia/vaultwarden
# slogan: Vaultwarden is a password manager that allows you to securely store and manage your passwords.
# tags: password manager, security
# logo: svgs/bitwarden.svg

services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      - SERVICE_FQDN_VAULTWARDEN
    volumes:
      - vaultwarden-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 2s
      timeout: 10s
      retries: 15
