# documentation: https://wordpress.org
# slogan: WordPress with MariaDB. Wordpress is open source software you can use to create a beautiful website, blog, or app.
# tags: cms, blog, content, management, mariadb
# logo: svgs/wordpress.svg

services:
   wordpress:
     image: wordpress:latest
     volumes:
       - wordpress-files:/var/www/html
     environment:
       - SERVICE_FQDN
       - WORDPRESS_DB_HOST=mariadb
       - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
       - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
       - WORDPRESS_DB_NAME=wordpress
     depends_on:
       - mariadb

   mariadb:
     image: mariadb:11
     volumes:
       - mariadb-data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
       - MYSQL_DATABASE=wordpress
       - MYSQL_USER=$SERVICE_USER_WORDPRESS
       - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
