# documentation: https://wordpress.org
# slogan: WordPress with external database. Wordpress is open source software you can use to create a beautiful website, blog, or app.
# tags: cms, blog, content, management
# logo: svgs/wordpress.svg

services:
   wordpress:
     image: wordpress:latest
     volumes:
       - wordpress-files:/var/www/html
     environment:
       - SERVICE_FQDN
